collection_name: "agent"
persist_directory: "chroma_db"
k: 3
data_path: "data"
md5_hex_store: "md5.text"
allow_knowledge_file_type: ["txt","pdf"]
# 分块大小
chunk_size: 200 
# 分块重叠大小
chunk_overlap: 20
# 分隔符
separators: ["\n","。","！","？","，","；","：","\n\n",".",","," ","","!","?"]
